import Foundation
import SwiftSDL

// =========================================================================
// MARK: - EngineInteractionManager
//
// Encapsulates all state related to user interaction with the viewport:
// dragging, rectangle selection, grips, double-clicking, and object picking.
// =========================================================================
@MainActor
public final class EngineInteractionManager {
    
    // MARK: - Drag State (tool interaction)
    
    public var dragActive: Bool = false
    public var dragLastWorldX: Double = 0
    public var dragLastWorldY: Double = 0
    public var dragLastScreenX: Float = 0
    public var dragLastScreenY: Float = 0
    public var dragStartAngle: Double = 0
    public var dragStartDistance: Double = 0
    
    /// Accumulated world-space delta during drag (for finalizing on mouse-up).
    public var dragTotalWorldX: Double = 0
    public var dragTotalWorldY: Double = 0
    
    /// Handles that are pending a full GPU vertex buffer regenerate after a drag.
    public var pendingPreviewHandles: Set<UUID> = []
    
    /// True if the pending preview was generated by a bulk drag (requires translation offset).
    public var pendingPreviewIsBulkDrag: Bool = false
    
    // Cursor position (updated every mouse-motion, used for zoom centering)
    public var lastMouseX: Float = 0
    public var lastMouseY: Float = 0
    
    // MARK: - Rectangle Select State
    
    public var rectSelectActive: Bool = false
    public var rectSelectStartX: Double = 0
    public var rectSelectStartY: Double = 0
    public var rectSelectScreenStartX: Float = 0  // screen-space X for L→R/R→L detection
    public var rectSelectCurrentX: Double = 0
    public var rectSelectCurrentY: Double = 0
    public var cadRectSelectMode: CADSelectionManager.RectSelectMode = .replace
    
    /// Handles that would be selected by the current rect (live preview).
    public var rectSelectPreviewHandles: Set<UUID> = []

    // MARK: - Object Picker Popup (multi-hit click)
    
    public var popupHitList: [(handle: UUID, label: String)] = []
    public var popupScreenX: Float = 0
    public var popupScreenY: Float = 0
    public var popupNeedsOpen: Bool = false

    // MARK: - Grip State

    public enum GripVertexEditMode: Sendable, Equatable {
        case stretch
        case lengthen
    }
    
    /// Whether the cursor is currently dragging a grip.
    public internal(set) var gripActive: Bool = false
    /// The type of grip being dragged.
    public internal(set) var gripType: CADSelectionManager.GripType = .center
    /// The entity whose grip is being dragged (CAD UUID).
    public internal(set) var gripHandle: UUID? = nil
    /// Document state before the current grip drag, used for one-step undo.
    public internal(set) var gripUndoSnapshot: CADDocumentSnapshot? = nil
    /// Document state before the current selection drag, used for one-step undo.
    public var dragUndoSnapshot: CADDocumentSnapshot? = nil
    
    /// Grip that the cursor is hovering over (for highlight).
    public internal(set) var hoveredGrip: CADSelectionManager.GripType? = nil
    public internal(set) var hoveredGripHandle: UUID? = nil
    
    /// Entity under the cursor (for hover highlight). nil when no geometry within threshold.
    public internal(set) var hoveredEntityHandle: UUID? = nil
    
    /// Last world-space position at which we performed a full `closestEntity` hit test.
    public var lastHoverTestWorldX: Double = -1e30
    public var lastHoverTestWorldY: Double = -1e30
    
    /// Accumulated rotation angle during grip drag (radians). Used to transform
    /// cached grip positions incrementally rather than recomputing from bounds.
    public var gripDragAccumRotation: Double = 0
    
    /// Accumulated scale factor during corner grip drag.
    public var gripDragAccumScale: Double = 1.0

    public internal(set) var gripVertexEditMode: GripVertexEditMode = .stretch
    public internal(set) var gripLengthenAnchor: Vector3? = nil
    public internal(set) var gripLengthenAxis: Vector3? = nil
    public internal(set) var gripAppliedWorldPosition: Vector3? = nil

    @discardableResult
    public func cycleGripVertexEditMode() -> Bool {
        guard gripActive,
              case .vertex(_, let index) = gripType,
              index < 1000,
              gripLengthenAnchor != nil,
              gripLengthenAxis != nil
        else { return false }

        gripVertexEditMode = gripVertexEditMode == .stretch ? .lengthen : .stretch
        return true
    }

    public func resetGripVertexEditMode() {
        gripVertexEditMode = .stretch
        gripLengthenAnchor = nil
        gripLengthenAxis = nil
        gripAppliedWorldPosition = nil
    }

    // MARK: - Data Table Editing

    public var selectedTableHandle: UUID? = nil
    public var tableSelectionRange: DataTableCellRange? = nil
    public var tableEditingMode: DataTableEditingMode = .table
    public var tableCellEditorActive: Bool = false
    public var tableCellEditBuffer: String = ""
    public var tableCellEditNeedsFocus: Bool = false
    public var hoveredTableBoundary: DataTableBoundaryHit? = nil

    public struct DataTableBoundaryDragState {
        public var handle: UUID
        public var boundary: DataTableBoundaryHit
        public var startLocalPoint: Vector3
        public var originalData: DataTableData
        public var undoSnapshot: CADDocumentSnapshot
        public var moved: Bool

        public init(
            handle: UUID,
            boundary: DataTableBoundaryHit,
            startLocalPoint: Vector3,
            originalData: DataTableData,
            undoSnapshot: CADDocumentSnapshot,
            moved: Bool = false
        ) {
            self.handle = handle
            self.boundary = boundary
            self.startLocalPoint = startLocalPoint
            self.originalData = originalData
            self.undoSnapshot = undoSnapshot
            self.moved = moved
        }
    }

    public var tableBoundaryDrag: DataTableBoundaryDragState? = nil

    public func selectTableCell(
        handle: UUID,
        address: DataTableCellAddress,
        extending: Bool
    ) {
        if extending, selectedTableHandle == handle, let current = tableSelectionRange {
            tableSelectionRange = DataTableCellRange(anchor: current.anchor, focus: address)
        } else {
            tableSelectionRange = DataTableCellRange(address)
        }
        selectedTableHandle = handle
        tableEditingMode = .cell
    }

    public func selectTable(handle: UUID) {
        selectedTableHandle = handle
        tableSelectionRange = nil
        tableEditingMode = .table
        tableCellEditorActive = false
        tableCellEditNeedsFocus = false
    }

    public func clearDataTableEditingState() {
        selectedTableHandle = nil
        tableSelectionRange = nil
        tableEditingMode = .table
        tableCellEditorActive = false
        tableCellEditBuffer = ""
        tableCellEditNeedsFocus = false
        hoveredTableBoundary = nil
        tableBoundaryDrag = nil
    }

    // MARK: - Double-Click Tracking
    
    /// Last left-click time (SDL ticks) for double-click detection.
    public var lastClickTime: UInt64 = 0
    /// Handle that was clicked last (for double-click detection).
    public var lastClickedHandle: UUID? = nil
    /// Screen position of last click (for double-click position check).
    public var lastClickScreenX: Float = 0
    public var lastClickScreenY: Float = 0
    
    // MARK: - Panning & Touch State
    
    /// Whether middle-mouse pan is active (independent of left-drag).
    public var panActive: Bool = false
    
    /// Active finger count for multi-touch panning.
    public var touchFingersDown: Int = 0
    /// Last average finger position (normalized 0-1), used to compute pan delta.
    public var lastTouchAvgX: Float = 0
    public var lastTouchAvgY: Float = 0
    /// Whether we are currently panning via touch.
    public var touchPanActive: Bool = false
    /// Whether the radial navigation control is holding an active pan gesture.
    public var radialPanActive: Bool = false
    
    public var forceHideOSCursor: Bool = false
    
    public var cachedGripGeneration: Int = -1

    public init() {}
}
